export enum API_PRODUCT {
    GET_ALL_PRODUCT = "GET_ALL_PRODUCT",
    ADD_PRODUCT = "ADD_PRODUCT",
    SEARCH_PRODUCT = "SEARCH_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    DELETE_PRODUCT = "DELETE_PRODUCT"
}